version: '3.8'

services:
  transaction-service:
    image: transaction-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - transaction-network

networks:
  transaction-network:
    driver: overlay 